#!/usr/bin/env python3
"""Export a Glassbox Annex IV vault (vault.save_json output) as a NIST OSCAL
Assessment Results document, validated with compliance-trestle.

Each vault entry becomes an OSCAL observation; entries with a pass/fail threshold
also become findings. EU AI Act articles are mapped to Glassbox-defined control IDs
(e.g. "Article 15(1)" -> "eu-ai-act-art-15.1"). There is no official OSCAL catalog
for the EU AI Act that this script knows of, so those IDs are local conventions.

    python vault_to_oscal.py annex-iv.json -o annex-iv.oscal-ar.json
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import uuid
from datetime import datetime, timezone

from trestle.oscal import assessment_results as ar
from trestle.oscal import common

NS = "https://glassbox-ai.dev/ns/oscal"
OSCAL_VERSION = "1.1.2"


def control_id(article: str) -> str:
    m = re.match(r"Article\s+(\d+)((?:\(\w+\))*)", article.strip())
    if not m:
        return "eu-ai-act-" + re.sub(r"[^a-z0-9]+", "-", article.lower()).strip("-")
    parts = re.findall(r"\((\w+)\)", m.group(2))
    return "eu-ai-act-art-" + ".".join([m.group(1), *parts]).lower()


def parse_time(s: str | None) -> datetime:
    if s:
        try:
            return datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        except ValueError:
            pass
    return datetime.now(timezone.utc)


def prop(name: str, value) -> common.Property:
    return common.Property(name=name, value=str(value), ns=NS)


def build(vault: dict, ap_href: str) -> ar.AssessmentResults:
    now = datetime.now(timezone.utc)
    observations, findings, controls = [], [], set()
    for e in vault["entries"]:
        ctrl_ids = [control_id(a) for a in e.get("article_refs", [])]
        controls.update(ctrl_ids)
        props = [prop("annex-iv-section", e["section"]), prop("evidence-type", e["evidence_type"])]
        if e.get("metric_name") is not None:
            props.append(prop("metric-name", e["metric_name"]))
        if e.get("metric_value") is not None:
            props.append(prop("metric-value", e["metric_value"]))
        if e.get("threshold") is not None:
            props.append(prop("threshold", e["threshold"]))
        obs_uuid = str(uuid.uuid4())
        observations.append(common.Observation(
            uuid=obs_uuid,
            title=e["title"],
            description=e["description"] or e["title"],
            props=props,
            methods=["TEST"] if e.get("metric_value") is not None else ["EXAMINE"],
            collected=parse_time(e.get("timestamp_utc")),
        ))
        # Article 11 is the duty to keep this documentation; a failed metric does not
        # make the documentation itself non-compliant, so it gets no finding.
        finding_ids = [c for c in ctrl_ids if c != "eu-ai-act-art-11"]
        if e.get("passed") is None or not finding_ids:
            continue
        for cid in finding_ids:
            findings.append(common.Finding(
                uuid=str(uuid.uuid4()),
                title=e["title"],
                description=e["description"] or e["title"],
                target=common.FindingTarget(
                    type="objective-id",
                    target_id=cid,
                    status=common.ObjectiveStatus(state="satisfied" if e["passed"] else "not-satisfied"),
                ),
                related_observations=[common.RelatedObservation(observation_uuid=obs_uuid)],
            ))

    summary = vault.get("compliance_summary", {})
    result = ar.Result(
        uuid=str(uuid.uuid4()),
        title=f"Glassbox Annex IV evidence for {vault.get('model_name', 'unknown model')}",
        description=(
            f"Generated by Glassbox {vault.get('glassbox_version', '?')} for provider "
            f"{vault.get('provider', '?')}, use case '{vault.get('use_case', '?')}'. "
            f"Glassbox quality-gate status: {summary.get('overall_status', 'n/a')} "
            "(a Glassbox threshold check, not a legal conformity assessment)."
        ),
        start=parse_time(vault.get("created_at")),
        end=now,
        props=[prop("model-name", vault.get("model_name")), prop("commit-sha", vault.get("commit_sha"))],
        reviewed_controls=common.ReviewedControls(control_selections=[
            common.ControlSelections(include_controls=[common.SelectControlById(control_id=c) for c in sorted(controls)])
            if controls else common.ControlSelectionsAll(include_all=common.IncludeAll())
        ]),
        observations=observations or None,
        findings=findings or None,
    )
    return ar.AssessmentResults(
        uuid=str(uuid.uuid4()),
        metadata=common.Metadata(
            title=f"EU AI Act Annex IV evidence — {vault.get('model_name', 'unknown')}",
            last_modified=now,
            version=str(vault.get("version", "1")),
            oscal_version=OSCAL_VERSION,
        ),
        import_ap=ar.ImportAp(href=ap_href),
        results=[result],
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("vault_json")
    ap.add_argument("--assessment-plan-href", default="#glassbox-assessment-plan",
                    help="href of the OSCAL assessment plan this result belongs to")
    ap.add_argument("-o", "--output", default="annex-iv.oscal-ar.json")
    args = ap.parse_args(argv)

    with open(args.vault_json) as fh:
        vault = json.load(fh)
    doc = build(vault, args.assessment_plan_href)
    doc.oscal_write(pathlib.Path(args.output))
    # Round-trip through the trestle model to prove the file validates.
    ar.AssessmentResults.oscal_read(pathlib.Path(args.output))
    res = doc.results[0]
    print(f"wrote {args.output}: {len(res.observations or [])} observations, "
          f"{len(res.findings or [])} findings, {len(getattr(res.reviewed_controls.control_selections[0], 'include_controls', None) or [])} controls (validated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
